name: Tests

on: 
  push:
    branches: ['main']

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        os: ['ubuntu-22.04']


    name: Run tests  
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests
    